#! /usr/bin/env sh

MIGRATION_RUNS_DIR=${MIGRATION_RUNS_DIR:-"${HOME}/.sh-migrate/${SCOPE:-global}"}
CHECKSUM_CMD=${CHECKSUM_CMD:-md5sum}

hashfn() {
	$CHECKSUM_CMD "$1" | cut -d' ' -f 1
}

check_sum() {
	checking_hash="$1"
	checking_file="$2"

	if ! [ "x$checking_hash" = "x$(hashfn "$checking_file")"]; then
		return 1
	fi

	return 0
}

while [ $# > 0 ]; do
	file="$(echo "$1" | cut -f: 1)"
	migration_name=$(echo "$1:" | cut -f: 2)
	migration_name=${migration_name:-$file}

	hash_val=$(hashfn "$file")

	if [ -e "$file" ]; then
		echo
	fi
done
